name: github actions cicd pipeline
on: 
    push: 
        branches: 
        - main
jobs:
    cicdtest:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2 
        - name: Build and Push Docker image
          run: | 
            docker build -t myimage . 
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker tag myimage abhi9d/myimage
            docker push abhi9d/myimage
        - name: Setup SSH Key
          run: |
              echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/ssh_key
              chmod 600 /tmp/ssh_key
 
        - name: Connect to EC2
          run: |
              ssh -o "StrictHostKeyChecking=no" -i /tmp/ssh_key  ubuntu@18.142.227.197 "
              kubectl delete deployment my-deployment
              kubectl apply -f /home/ubuntu/my-deployment.yml
              "    
